#!/bin/bash

DICT="/usr/share/dict/american-english"

sed "s/'s\$//" $DICT | tr 'A-Z' 'a-z' | egrep '^[a-z0-9]{,10}$' | sort | uniq \
  | sed 's/.*/"\0",/' | tr -d '\n' | sed 's/^\(.*\),$/[\1]/' > wordlist.json
